#!/bin/bash

# MySQL database credentials

DB_USER="username"

DB_PASSWORD="password"

DB_NAME="database_name"

# SQL queries to execute

QUERY_1="SELECT * FROM table1;"

QUERY_2="SELECT * FROM table2;"

QUERY_3="UPDATE table1 SET column1='value1' WHERE id=1;"

QUERY_4="INSERT INTO table2 (column1, column2) VALUES ('value1', 'value2');"

# Execute the queries

mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME -e "$QUERY_1"

mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME -e "$QUERY_2"

mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME -e "$QUERY_3"

mysql -u$DB_USER -p$DB_PASSWORD $DB_NAME -e "$QUERY_4"

